const GAME_DATA = [
  {
    id: "direct_indirect_quiz",
    title: "Direct and Indirect Questions",
    match: "Décimo A VS Décimo B",
    defaultTeams: ["Décimo A", "Décimo B"],
    topics: ["Direct and Indirect Questions"],
    questions: [
      { type:"Direct and Indirect Questions", visual:"❓", q:"What is your name?", a:"Could you tell me what your name is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where do you live?", a:"Do you know where you live?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Are you studying English?", a:"Could you tell me if you are studying English?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Do you like pizza?", a:"I wonder if you like pizza." },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Have you finished your homework?", a:"Could you tell me if you have finished your homework?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where is the nearest library?", a:"Could you tell me where the nearest library is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What are you doing now?", a:"Do you know what you are doing now?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Will you come to the party?", a:"Could you tell me if you will come to the party?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"When does the train leave?", a:"Do you know when the train leaves?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Why is she late?", a:"I wonder why she is late." },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What did you eat for breakfast?", a:"Could you tell me what you ate for breakfast?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Have they visited Paris?", a:"Do you know if they have visited Paris?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where did you go yesterday?", a:"Could you tell me where you went yesterday?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who is your best friend?", a:"Could you tell me who your best friend is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Why are they upset?", a:"Do you know why they are upset?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Are they watching TV?", a:"Could you tell me if they are watching TV?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Did you enjoy the movie?", a:"Do you know if you enjoyed the movie?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What will you do tomorrow?", a:"Could you tell me what you will do tomorrow?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Is she coming to the meeting?", a:"Do you know if she is coming to the meeting?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"How often do you play football?", a:"Could you tell me how often you play football?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Have you ever visited London?", a:"Do you know if you have ever visited London?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What time did the bus arrive?", a:"Could you tell me what time the bus arrived?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who wrote this book?", a:"Do you know who wrote this book?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where can I find the supermarket?", a:"Could you tell me where I can find the supermarket?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Will it rain tomorrow?", a:"Do you know if it will rain tomorrow?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Did she call you?", a:"Could you tell me if she called you?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who is responsible for this task?", a:"Could you tell me who is responsible for this task?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"When did they arrive?", a:"Do you know when they arrived?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Why is he angry?", a:"I wonder why he is angry." },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What did you say?", a:"Could you tell me what you said?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Are we allowed to enter?", a:"Do you know if we are allowed to enter?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where did she buy that dress?", a:"Could you tell me where she bought that dress?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who is the president of the club?", a:"Do you know who the president of the club is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What are your plans for the weekend?", a:"Could you tell me what your plans for the weekend are?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Have you read this book?", a:"Do you know if you have read this book?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where did he go last summer?", a:"Could you tell me where he went last summer?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Is she your sister?", a:"Do you know if she is your sister?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"When will they arrive?", a:"Could you tell me when they will arrive?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Why did you leave early?", a:"Do you know why you left early?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"How do you make this recipe?", a:"Could you tell me how you make this recipe?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who called you yesterday?", a:"Do you know who called you yesterday?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What did they eat for dinner?", a:"Could you tell me what they ate for dinner?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Have you ever been to Paris?", a:"Do you know if you have ever been to Paris?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where is the nearest hospital?", a:"Could you tell me where the nearest hospital is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What are they doing now?", a:"Do you know what they are doing now?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Did he enjoy the party?", a:"Could you tell me if he enjoyed the party?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Where can I buy tickets?", a:"Do you know where I can buy tickets?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"Who is your teacher?", a:"Could you tell me who your teacher is?" },
      { type:"Direct and Indirect Questions", visual:"❓", q:"What time does the movie start?", a:"Do you know what time the movie starts?" }
    ]
  }
];