const GAME_DATA = [
  {
    id: "fuselaje_quiz",
    title: "Vida Integral del Creyente",
    match: "Adolescentes VS Clase",
    defaultTeams: ["Equipo A", "Equipo B"],
    topics: ["Espíritu", "Alma", "Cuerpo", "Todo"],
    questions: [
      // Espíritu (10)
      { type:"Espíritu", visual:"🙏", q:"¿Cuál es la acción principal para fortalecer tu espíritu?", a:"Orar y buscar a Dios" },
      { type:"Espíritu", visual:"📖", q:"¿Qué actividad ayuda a conocer la voluntad de Dios?", a:"Leer la Biblia" },
      { type:"Espíritu", visual:"🎵", q:"¿Cómo podemos adorar a Dios diariamente?", a:"Cantando y alabando con el corazón" },
      { type:"Espíritu", visual:"🕊️", q:"¿Qué fruto se evidencia cuando el espíritu está alineado con Dios?", a:"Paz y alegría" },
      { type:"Espíritu", visual:"💡", q:"¿Cuál es un hábito que fortalece la relación con Dios?", a:"Reflexión y oración diaria" },
      { type:"Espíritu", visual:"🤲", q:"¿Qué significa entregar nuestra vida a Dios?", a:"Confiar y obedecerlo en todo" },
      { type:"Espíritu", visual:"⏰", q:"¿Cuándo debemos buscar a Dios?", a:"Todos los días y en todo momento" },
      { type:"Espíritu", visual:"🗣️", q:"¿Cómo expresamos nuestra fe de manera auténtica?", a:"Compartiendo y testificando" },
      { type:"Espíritu", visual:"❤️", q:"¿Qué actitud refleja un espíritu alineado con Dios?", a:"Amor y humildad" },
      { type:"Espíritu", visual:"🌟", q:"¿Qué debemos permitir que Dios haga en nuestra vida?", a:"Guiar y transformar todo nuestro ser" },
      
      // Alma (10)
      { type:"Alma", visual:"🧠", q:"¿Qué debemos cuidar en nuestra mente?", a:"Pensamientos positivos y de fe" },
      { type:"Alma", visual:"💭", q:"¿Qué emoción debemos entregar a Dios?", a:"Ansiedad, miedo o resentimiento" },
      { type:"Alma", visual:"📝", q:"¿Cómo podemos tomar decisiones correctas?", a:"Buscando la guía de Dios" },
      { type:"Alma", visual:"🤝", q:"¿Qué actitud ayuda a mantener relaciones sanas?", a:"Perdón y comprensión" },
      { type:"Alma", visual:"😌", q:"¿Qué hábito fortalece la estabilidad emocional?", a:"Meditación en la Palabra de Dios" },
      { type:"Alma", visual:"🌱", q:"¿Qué significa renovar nuestra mente?", a:"Cambiar pensamientos negativos por los de Dios" },
      { type:"Alma", visual:"🛡️", q:"¿Qué debemos usar para proteger nuestra alma?", a:"La fe y la verdad de Dios" },
      { type:"Alma", visual:"🔥", q:"¿Qué debemos evitar que domine nuestra alma?", a:"La ira, envidia o orgullo" },
      { type:"Alma", visual:"💡", q:"¿Cómo discernimos entre lo bueno y lo malo para nuestra alma?", a:"Aplicando los principios bíblicos" },
      { type:"Alma", visual:"🕊️", q:"¿Qué refleja un alma alineada con Dios?", a:"Serena, confiada y llena de esperanza" },
      
      // Cuerpo (10)
      { type:"Cuerpo", visual:"🏃", q:"¿Qué representa cuidar nuestro cuerpo?", a:"Hábito, salud y obediencia a Dios" },
      { type:"Cuerpo", visual:"🍎", q:"¿Qué hábitos alimenticios reflejan disciplina?", a:"Comer sano y moderadamente" },
      { type:"Cuerpo", visual:"🛌", q:"¿Cómo reflejamos cuidado físico y espiritual?", a:"Descansando y evitando excesos" },
      { type:"Cuerpo", visual:"💪", q:"¿Qué demuestra coherencia entre espíritu y cuerpo?", a:"Obedecer a Dios en acciones y conducta" },
      { type:"Cuerpo", visual:"🗣️", q:"¿Cómo debemos usar nuestra boca?", a:"Para bendecir, hablar la verdad y alabar" },
      { type:"Cuerpo", visual:"📱", q:"¿Qué debemos vigilar en nuestra conducta diaria?", a:"Uso de redes y entretenimiento" },
      { type:"Cuerpo", visual:"👕", q:"¿Cómo refleja nuestro cuerpo lo que somos por dentro?", a:"Con acciones coherentes y hábitos correctos" },
      { type:"Cuerpo", visual:"⏳", q:"¿Qué importancia tiene la disciplina física?", a:"Para servir a Dios mejor y estar saludables" },
      { type:"Cuerpo", visual:"🎯", q:"¿Qué decisiones afectan la integridad del cuerpo?", a:"Hábitos diarios y relaciones" },
      { type:"Cuerpo", visual:"🔑", q:"¿Qué es clave para mantener el cuerpo alineado con Dios?", a:"Dominio propio y obediencia" },
      
      // Todo (30)
      { type:"Todo", visual:"🌐", q:"¿Qué es la vida integral del creyente?", a:"La unión de espíritu, alma y cuerpo alineados con Dios" },
      { type:"Todo", visual:"🌟", q:"¿Por qué Dios quiere que todo nuestro ser esté alineado?", a:"Porque somos su vehículo para obrar" },
      { type:"Todo", visual:"❤️", q:"¿Qué refleja una vida integral?", a:"Coherencia, paz y obediencia" },
      { type:"Todo", visual:"🕊️", q:"¿Qué áreas deben estar alineadas con Dios?", a:"Espíritu, alma y cuerpo" },
      { type:"Todo", visual:"🙏", q:"¿Qué hábito fortalece el espíritu y cuerpo?", a:"Oración diaria" },
      { type:"Todo", visual:"📖", q:"¿Qué debemos leer para fortalecer nuestra vida integral?", a:"La Biblia" },
      { type:"Todo", visual:"💭", q:"¿Qué debemos entregar a Dios de nuestra alma?", a:"Pensamientos negativos y emociones dañinas" },
      { type:"Todo", visual:"🏃", q:"¿Qué refleja cuidado del cuerpo y obediencia?", a:"Hábitos saludables y disciplina" },
      { type:"Todo", visual:"📝", q:"¿Cómo tomar decisiones correctas?", a:"Buscando la guía de Dios" },
      { type:"Todo", visual:"🎵", q:"¿Qué acción diaria fortalece la adoración?", a:"Alabar y cantar con el corazón" },
      { type:"Todo", visual:"🌱", q:"¿Qué significa renovar nuestra mente?", a:"Cambiar pensamientos negativos por principios de Dios" },
      { type:"Todo", visual:"💡", q:"¿Qué actitud refleja un alma alineada?", a:"Esperanza y serenidad" },
      { type:"Todo", visual:"🔥", q:"¿Qué debemos evitar que domine nuestra vida?", a:"Ira, orgullo y envidia" },
      { type:"Todo", visual:"💪", q:"¿Qué demuestra coherencia entre cuerpo y espíritu?", a:"Obedecer a Dios y cuidar hábitos" },
      { type:"Todo", visual:"⏰", q:"¿Cuándo debemos buscar a Dios?", a:"Todos los días" },
      { type:"Todo", visual:"🤲", q:"¿Qué significa entregar nuestra vida?", a:"Confiar y obedecer a Dios" },
      { type:"Todo", visual:"🛡️", q:"¿Qué debemos usar para proteger nuestra alma?", a:"La fe y la verdad de Dios" },
      { type:"Todo", visual:"🤝", q:"¿Qué actitud ayuda a mantener relaciones sanas?", a:"Perdón y comprensión" },
      { type:"Todo", visual:"📱", q:"¿Qué debemos vigilar para el cuerpo y alma?", a:"Uso de redes y entretenimiento" },
      { type:"Todo", visual:"🎯", q:"¿Qué decisiones afectan nuestra integridad?", a:"Hábitos diarios, pensamientos y relaciones" },
      { type:"Todo", visual:"🔑", q:"¿Qué es clave para mantener la vida integral alineada?", a:"Dominio propio y obediencia" },


       // Espíritu, Alma, Cuerpo, Todo: (se mantiene igual)
      // Biblia: 30 preguntas añadidas al final
      { type:"Biblia", visual:"📖", q:"¿Cuántos libros tiene el Nuevo Testamento?", a:"27" },
      { type:"Biblia", visual:"📖", q:"¿Cuál es el versículo más largo de la Biblia?", a:"Éster 8:9" },
      { type:"Biblia", visual:"📖", q:"¿Cómo se llamaba el padre de Sansón?", a:"Manao" },
      { type:"Biblia", visual:"📖", q:"¿Quién construyó el arca?", a:"Noé" },
      { type:"Biblia", visual:"📖", q:"¿Cuántos días y noches llovió durante el diluvio?", a:"40" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue la primera persona en pecar?", a:"Adán" },
      { type:"Biblia", visual:"📖", q:"¿Cuál fue el primer milagro de Jesús?", a:"Convertir agua en vino" },
      { type:"Biblia", visual:"📖", q:"¿Qué profeta fue tragado por un gran pez?", a:"Jonás" },
      { type:"Biblia", visual:"📖", q:"¿Quién interpretó los sueños del faraón?", a:"José" },
      { type:"Biblia", visual:"📖", q:"¿Cuántos discípulos tuvo Jesús?", a:"12" },
      { type:"Biblia", visual:"📖", q:"¿Quién recibió los Diez Mandamientos?", a:"Moisés" },
      { type:"Biblia", visual:"📖", q:"¿Qué rey escribió muchos de los Salmos?", a:"David" },
      { type:"Biblia", visual:"📖", q:"¿Qué libro cuenta la historia de Rut?", a:"Rut" },
      { type:"Biblia", visual:"📖", q:"¿Qué personaje fue famoso por su gran paciencia?", a:"Job" },
      { type:"Biblia", visual:"📖", q:"¿Quién traicionó a Jesús por 30 monedas de plata?", a:"Judas Iscariote" },
      { type:"Biblia", visual:"📖", q:"¿Qué mar se abrió para que los israelitas cruzaran?", a:"Mar Rojo" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue conocido como el hombre más sabio de Israel?", a:"Salomón" },
      { type:"Biblia", visual:"📖", q:"¿Qué profeta desafió a los profetas de Baal en el monte Carmelo?", a:"Elías" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue liberado de la cueva de los leones?", a:"Daniel" },
      { type:"Biblia", visual:"📖", q:"¿Cuál es el primer libro de la Biblia?", a:"Génesis" },
      { type:"Biblia", visual:"📖", q:"¿Qué discípulo negó a Jesús tres veces?", a:"Pedro" },
      { type:"Biblia", visual:"📖", q:"¿Qué río se convirtió en sangre en Egipto?", a:"Nilo" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue elevado al cielo sin morir?", a:"Enoc y Elías" },
      { type:"Biblia", visual:"📖", q:"¿Cuál es el último libro de la Biblia?", a:"Apocalipsis" },
      { type:"Biblia", visual:"📖", q:"¿Qué alimento proporcionó Dios a los israelitas en el desierto?", a:"Maná" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue vendido como esclavo por sus hermanos?", a:"José" },
      { type:"Biblia", visual:"📖", q:"¿Qué mujer salvó a su pueblo engañando al rey Asuero?", a:"Ester" },
      { type:"Biblia", visual:"📖", q:"¿Qué profeta fue llamado ‘el profeta llorón’?", a:"Jeremías" },
      { type:"Biblia", visual:"📖", q:"¿Quién fue conocido por su fuerza y luchas contra los filisteos?", a:"Sansón" },
      { type:"Biblia", visual:"📖", q:"¿Cuál es el primer milagro que realizó Moisés?", a:"Convertir su vara en serpiente" }
    ]
  }
];